### PR TITLE
Garlic oil and a few food items

### PR DESCRIPTION
**Pull request by chaosvolt**
* Add roasted garlic and chili peppers. Basic recipes to season some underused food items and make them more edible.
* Added garlic bread! Fairly basic but yet another option for using garlic in recipes.
* Garlic oil, AKA Russian Penicillin. Uses the `WEAK_ANTIBIOTIC` effect, but with a minor healthiness bonus instead of a penalty, meaning it should be just barely above weak antibiotic in effectiveness in practice.

### CODE REVIEW

**Comment by Maddremor** [comment]
Are you sure you're not thinking of garlic oil being antiseptic akin to thyme oil?

**Comment by chaosvolt** [comment]
Back in the old days I actually added garlic to bandages as an option for disinfectant, in More Survival Tools itself. It got removed for "gibe realism pls" reasons, and when I looked into it there was some discussion here: https://github.com/CleverRaven/Cataclysm-DDA/pull/22972

The sources linked indeed lean more in favor of oral use more than topical, with the most trustworthy one being: https://academic.oup.com/jac/article/43/6/837/754741 I then did some searching of my own and found this: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3249897/ The most relevant section being:

```
The French phytotherapist Lecraec used garlic tincture in treatment of a patient with pulmonary gangrene. The patient recovered in 17 days.
```

Treatment of gangrene is the sort of thing players are likely thinking of when they're trying to treat an infected wound. And right now there's not many ways to model topical applications that can treat a full-blown infection, at least in a way that requires *prolonged* treatment, as even using the `heal` use action with a low chance to clear infection (like a nerfed version of what first aid kits used to do) what just be an all-or-nothing roll of the dice.

If anything I might test whether I can give garlic oil two use_actions. One for use on bites, another for infections. Either that, or allowing garlic oil to be used for sterilizing bandages or for some other disinfectant recipe. Either way, `WEAK_ANTIBIOTIC` seems to be best used on a bite wound to maximize how many rolls of the dice it affects. If you use either atreypan or garlic oil on a green infection it seems you're basically sacrificing your life to the Random Number God and hoping you get it handed back to you. XP

**Comment by chaosvolt** [comment]
Had some further discussion in DM, that has left me thinking this is likely okay but it might be better to have topical use as well, and possibly some method of using it for makeshift bandages.

**Comment by chaosvolt** [comment]
Belated discovery. Trying to give garlic oil both `WEAK_ANTIBIOTIC` and a `heal` use action doesn't work, as it wants to insist on only being eaten, not applied (even with comestible type `MED`).

I can still make it usable for some form of makeshift first aid item, though.

**Pull request merged**
