### PR TITLE
adds units to max_volume

### PR DESCRIPTION
**Pull request by ephemeralstoryteller**
Appeases fussy gods of code and their unit conventions, thus ensuring a bountiful harvest for next season

### CODE REVIEW

**Comment by chaosvolt** [comment]
I've been meaning to tackle this for a while but been juggling other things, thank you. Are they already making this mandatory?

**Comment by ephemeralstoryteller** [comment]
No problem! I really like your mods so I figured I'd help by doing some groundwork. ^w^ 

There was a change that added some framework for using units for everything, which semi unintentionally made the game throw an error with the latest updates. So tl;dr yeah, I think so.

**Comment by chaosvolt** [comment]
Hmm. I might need to set out to add conversions for more stuff then. Is it only being an issue for furniture, or is it mandatory for items too?

**Comment by ephemeralstoryteller** [comment]
This is only an issue for furniture as far as I'm aware. Items seem to be doing fine how you have them now!

**Pull request merged**
